### PR TITLE
[EV-748] Pass res to getBlockReward to avoid uncaught exception on error

### PR DESCRIPTION
**Pull request by gilemon**
fix for EV-748 Insight-API: Uncaught Exception - RefError - Res is not defined

### CODE REVIEW

**Comment by nmarley** [comment]
This auto-closed when I removed `develop`, I have set `master` as base branch and re-opening here on that basis. Not sure if this actually is still needed or not.

**Comment by nmarley** [comment]
Just an FYI, this will need to be rebased onto the latest master (please do a manual rebase and force-push) for review / consideration for merging.

**Comment by Cofresi** [comment]
This error seems to not have happened for a long time now and it is possible that it's already resolved by something else we did. Also, I'm not convinced that inserting `res` in these four places would solve the underlying root cause of the error. I would not merge it into the new release and wait for it to pop up again unless Gilemon responds to the below:

@gilemon from your comment here https://dashpay.atlassian.net/projects/EV/issues/EV-748 you say you were able to reproduce the error. Can you specify what you mean exactly by `by injecting a bad previousblockhash`? I was not able to find any possibility to specify a previous blockhash in the api's endpoints.

**Comment by Cofresi** [comment]
Closing this as it was replaced by https://github.com/dashevo/insight-api/pull/61

**Pull request closed without merging**
