### PR TITLE
security: npm audit fix & chore: update deps

### PR DESCRIPTION
**Pull request by coolaj86**

### CODE REVIEW

**Comment by coolaj86** [comment]
## Note

Should probably let https://github.com/dashpay/dashcore-node/pull/96 get pulled and deployed first so that when this is pulled and deployed it will come after - because of the bespoke (non-npm) `dashcore-node` dependency management.

**Comment by coolaj86** [comment]
@shumkov @pshenmic  ^^

**Review by ktechmidas — APPROVED** [review]
LGTM

**Review by strophy — APPROVED** [review]

**Review by shumkov — APPROVED** [review]
👍

**Pull request merged**
